version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/Pinterest/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/data/static
      - media_volume:/data/media
    networks:
      - nginx-django
    depends_on:
      - pinterest-app

  pinterest-app:
    container_name: pinterest-app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/home/Pinterest/static
      - media_volume:/home/Pinterest/media
    networks:
      - nginx-django

networks:
  nginx-django:
    driver: bridge

volumes:
  static_volume:
  media_volume: